### ISSUE TITLE
About Error: No such file or directory

### ISSUE THREAD

**Issue by srmzzz** [aemon-j/LER_examples#13]
The exmples of Feeagh, Erken and Mendota were successful, but I failed in Giles, Langtjern and my lake.  The error noted: no output file. And my lake even failed at Flake. At first, I think maybe I set a wrong directory. After many attempts, I guess the reason is lack of inflow data or other necessary input files. So it can't get the output. 
This issues maybe silly, but plagued me all the time as a R alnguage beginner. Please tell me whether my guess correct. Thank you a lot.
![v2-bfc6e4da4b765190706b70bced67f44f_720w](https://user-images.githubusercontent.com/60535413/111292552-41572500-8683-11eb-9f22-b699704ac86e.jpg)

```
library(LakeEnsemblR)
setwd("D:/R_lake/lac_test/example/LER_examples/LakeGiles") # Change working directory to example folder
# Set config file & models
config_file <- 'Giles_master_config.yaml'
model <- c("FLake", "GLM", "GOTM", "Simstrat", "MyLake")
# Example run
# 1. Export settings - creates directories with all model setups and exports settings from the LER configuration file
export_config(config_file = config_file, model = model)
# 2. Run ensemble lake models
run_ensemble(config_file = config_file, model = model)

```
The states after run_ensemble() 
```
Loading water temperature observations...[2021-03-16 09:39:55]
Finished loading water temperature observations![2021-03-16 09:39:55]
Running models... (Have you tried parallelizing?) [2021-03-16 09:39:55]
FLake run is complete! [2021-03-16 09:39:55]
GLM run is complete! [2021-03-16 09:39:55]
Error in R_nc4_open: No such file or directory
Error in nc_open(file, readunlim = TRUE) : 
 Error in nc_open trying to open file `./GLM/output/output.nc
```

**Comment by JFeldbauer** [comment]
hello,
thank you for noticing this and letting us know. I can reproduce the error you experience and I think this is our fault as we did not update the configuration files for Giles and Langtjern. You can fix this by changing the config files for the two lakes and setting the `mass-balance` argument in the `inflows` section to `false`. This should be done automatically as there are no inflows, but it seems this is not working properly. Thank you for reporting this.

Please let me know if this solves you problem.

Cheers, Johannes

**Comment by jorritmesman** [comment]
Hi,

Either the solution mentioned above works, or installing the latest version of LakeEnsemblR (https://github.com/aemon-j/LakeEnsemblR/pull/226). This was indeed a bug, but now if "use/inflows" is set to "false", as in the Giles and Langtjern examples, there should no longer be issues. 

Once again, thanks for letting us know and apologies for the problems.

Cheers,
Jorrit

**Comment by srmzzz** [comment]
Thanks for your answers. My problem has been sloved. You guys really provide a great convenience to run model. Many thanks.
